const Info =  {
    name: "Vivek Jha",
    stack: ["Software Engineer", "Full Stack Developer", "Competitive Programmer", "Freelancer"],
    bio: "I'm a Software Engineer, Full Stack Developer, Competitive Programmer and Freelancer. I'm a tech enthusiast and love to explore new technologies. I'm a quick learner and always ready to learn new things. I'm a team player and always ready to help others. I'm a problem solver and always ready to solve problems. I'm a hard worker and always ready to work hard.",
}

const ProjectInfo = [
    {
        title: "Portfolio",
        description: "This is my portfolio website. It is built using React, TypeScript, Tailwind CSS and Vanta.js. It is a responsive website and works on all devices.",
        image: "project1.png",
        live: true,
        github: "www.github.com/Vivek-Jha-05",
        link: "www.github.com/Vivek-Jha-05",
        techStack: ["React", "TypeScript", "Tailwind CSS", "Vanta.js"],
        type: "Web",
        status: "Completed",
    },
    {
        title: "Personal Website",
        description: "This is my personal website. It is built using HTML, CSS, JavaScript and Bootstrap. It is a responsive website and works on all devices.",
        image: "project2.png",
        live: true,
        github: "www.github.com/Vivek-Jha-05",
        link: "www.github.com/Vivek-Jha-05",
        techStack: ["HTML", "CSS", "JavaScript", "Bootstrap"],
        type: "Web",
        status: "Completed",
    },
    {
        title: "Quiz App",
        description: "This is a quiz app. It is built using React, TypeScript, Tailwind CSS and Vanta.js. It is a responsive website and works on all devices.",
        image: "project3.png",
        live: true,
        github: "www.github.com/Vivek-Jha-05",
        link: "www.github.com/Vivek-Jha-05",
        techStack: ["React", "TypeScript", "Tailwind CSS", "Vanta.js"],
        type: "Web",
        status: "Completed",
    },
    {
        title: "Portfolio",
        description: "This is my portfolio website. It is built using React, TypeScript, Tailwind CSS and Vanta.js. It is a responsive website and works on all devices. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "project1.png",
        live: true,
        github: "www.github.com/Vivek-Jha-05",
        link: "www.github.com/Vivek-Jha-05",
        techStack: ["React", "TypeScript", "Tailwind CSS", "Vanta.js"],
        type: "Web",
        status: "Completed",
    },
    {
        title: "Personal Website",
        description: "This is my personal website. It is built using HTML, CSS, JavaScript and Bootstrap. It is a responsive website and works on all devices.",
        image: "project2.png",
        live: true,
        github: "www.github.com/Vivek-Jha-05",
        link: "www.github.com/Vivek-Jha-05",
        techStack: ["HTML", "CSS", "JavaScript", "Bootstrap"],
        type: "Web",
        status: "Completed",
    },
    {
        title: "Quiz App",
        description: "This is a quiz app. It is built using React, TypeScript, Tailwind CSS and Vanta.js. It is a responsive website and works on all devices.",
        image: "project3.png",
        live: true,
        github: "www.github.com/Vivek-Jha-05",
        link: "www.github.com/Vivek-Jha-05",
        techStack: ["React", "TypeScript", "Tailwind CSS", "Vanta.js"],
        type: "Web",
        status: "Completed",
    }
]

const SkillInfo = [
    {
        title: "Frontend",
        skills: ["HTML", "CSS", "JavaScript", "React", "TypeScript", "Tailwind CSS", "Bootstrap", "Material UI", ],
    },
    {
        title: "Backend",
        skills: ["Node.js", "Express.js", "MongoDB", "MySQL", "PostgreSQL", "Firebase", "GraphQL"],
    },
    {
        title: "Programming Languages",
        skills: ["C", "C++", "Java", "Python", "JavaScript", "TypeScript"],
    },
    {
        title: "Competitive Programming",
        skills: ["LeetCode", "HackerRank", "CodeChef", "Codeforces"],
    },
    {
        title: "tools",
        skills: ["Git", "GitHub", "Docker", "Kubernetes", "AWS", "Azure", "Google Cloud"],
    }
]

const ExperienceInfo = [
    {
        role: "Software Engineer",
        company: "Google",
        date: "Jan 2022 - Present",
        description: "Working as a Software Engineer at Tech Company. Responsible for developing and maintaining web applications using React, Node.js and MongoDB.",
        skills: ["React", "Node.js", "MongoDB", "Express.js"],
    },
    {
        role: "Intern",
        company: "Google",
        date: "Jun 2021 - Dec 2021",
        description: "Worked as an intern at Internship Company. Developed a web application using React and Node.js. Gained experience in web development and learned about software development lifecycle.",
        skills: ["React", "Node.js", "MongoDB", "Express.js"],
    },
    {
        role: "Freelancer",
        company: "Google",
        date: "Jan 2020 - May 2021",
        description: "Worked on various freelance projects. Developed web applications using React, Node.js and MongoDB. Gained experience in web development and learned about software development lifecycle.",
        skills: ["React", "Node.js", "MongoDB", "Express.js"],
    }
]

// const Slugs = [
//     "typescript",
//     "javascript",
//     "react",
//     "nodejs",
//     "html",
//     "css",
//     "python",
//     "java",
//     "c++",
//     "c",
//     "mongodb",
//     "mysql",
//     "postgresql",
//     "firebase",
//     "graphql",
//     "docker",
//     "kubernetes",
//     "aws",
//     "azure",
//     "google-cloud",
//     "git",
//     "github",
//     "leetcode",
//     "hackerrank",
//     "codechef",
//     "android",
//     "flutter",
//     "vanta-js",
//     "tailwind-css",
//     "bootstrap",
//     "material-ui",
//     "express-js",
//     "vercel",
//     "netlify",

// ]

const Slugs = [
    "mongodb",
    "vanta",
    "tailwindcss",
    "bootstrap",
    "aws",
    "kubernetes",
    "azure",
    "googlecloud",
  "mysql",
  "typescript",
  "javascript",
  "dart",
  "java",
  "react",
  "flutter",
  "android",
  "html5",
  "css3",
  "nodedotjs",
  "express",
  "nextdotjs",
  "prisma",
  "amazonaws",
  "postgresql",
  "firebase",
  "nginx",
  "vercel",
  "testinglibrary",
  "jest",
  "cypress",
  "docker",
  "git",
  "jira",
  "github",
  "gitlab",
  "visualstudiocode",
  "androidstudio",
  "sonarqube",
  "figma",
];

export {Info, ProjectInfo, SkillInfo, ExperienceInfo, Slugs};
